addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libfftw3-dev
      - libfribidi-dev

language: r

dist: bionic

cache: packages

r_packages:
  - pkgdown

after_success:
  - R CMD INSTALL .
  - Rscript -e "pkgdown::build_site(preview = FALSE)"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
