# DEVELOPER NOTE:
# Snapshots generated by the following tests can contain sensitive data and are
# therefore only stored locally via gitignore in the folder _snaps/. See the
# testing README for the recommended workflow.

test_that("get_locs, get_xg3 and get_chem work with default filters and dwh settings", {
  suppressWarnings({
    file_names <- c(
      "locs",
      "obswells",
      "xg3",
      "chem"
    )
    announce_files_migration(file_names)

    skip_if(getOption("test.skip_dwh_migration"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types
    )
    expect_migration(locs, "locs")

    obswells <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      obswells = TRUE
    )
    expect_migration(obswells, "obswells")

    xg3 <- locs %>% get_xg3(watina, 2010) %>% collect()
    expect_migration(xg3, "xg3")

    chem <- locs %>% get_chem(watina, "1/1/2017") %>% collect()
    expect_migration(chem, "chem")
  })
})

test_that("get_locs works with different filters and dwh settings", {
  suppressWarnings({
    file_names <- c(
      "locs_area_codes",
      "locs_bbox",
      "locs_mask",
      "locs_filterdepth_guess",
      "locs_filterdepth_na"
    )
    announce_files_migration(file_names)

    skip_if(getOption("test.skip_dwh_migration"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      area_codes = c("KAL", "ZWA")
    )
    expect_migration(locs, "locs_area_codes")

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      bbox = c(xmin = 1.4e+5, xmax = 1.7e+5, ymin = 1.6e+5, ymax = 1.9e+5)
    )
    expect_migration(locs, "locs_bbox")

    wfs_url <- "https://geo.api.vlaanderen.be/VRBG/wfs" %>%
      httr2::request() %>%
      httr2::req_url_query(
        request = "GetFeature",
        typeName = "VRBG:Refprv",
        cql_filter = "NAAM='West-Vlaanderen'",
        srsName = "EPSG:31370",
        outputFormat = "text/xml; subtype=gml/3.1.1"
      )
    mymask <- sf::read_sf(wfs_url$url, crs = 31370) %>%
      sf::st_cast("GEOMETRYCOLLECTION")
    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      mask = mymask,
      buffer = 0,
      collect = TRUE
    )
    expect_migration(locs, "locs_mask")

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      filterdepth_guess = TRUE
    )
    expect_migration(locs, "locs_filterdepth_guess")

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      filterdepth_na = TRUE
    )
    expect_migration(locs, "locs_filterdepth_na")
  })
})

test_that("get_locs applies different aggregation logic correctly with dwh settings", {
  suppressWarnings({
    file_names <- c(
      "locs_obswell_aggr_latest",
      "locs_obswell_aggr_latest_fd",
      "locs_obswell_aggr_latest_sso",
      "locs_obswell_aggr_mean"
    )
    announce_files_migration(file_names)

    skip_if(getOption("test.skip_dwh_migration"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "latest"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_migration(locs, "locs_obswell_aggr_latest")

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "latest_fd"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_migration(locs, "locs_obswell_aggr_latest_fd")

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "latest_sso"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_migration(locs, "locs_obswell_aggr_latest_sso")

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types,
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "mean"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_migration(locs, "locs_obswell_aggr_mean")
  })
})

test_that("get_gx3 works with different filters and dwh settings", {
  suppressWarnings({
    file_names <- c(
      "xg3_ostend",
      "xg3_both",
      "xg3_year_range",
      "xg3_local_locs"
    )
    announce_files_migration(file_names)

    skip_if(getOption("test.skip_dwh_migration"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      loc_vec = dwh_test_locations,
      loc_validity = dwh_test_validity,
      loc_type = dwh_test_types
    )

    xg3_ostend <- locs %>%
      get_xg3(watina, 2010, vert_crs = "ostend") %>%
      collect()
    expect_migration(xg3_ostend, "xg3_ostend")

    xg3_both <- locs %>% get_xg3(watina, 2010, vert_crs = "both") %>% collect()
    expect_migration(xg3_both, "xg3_both")

    xg3_range <- locs %>%
      get_xg3(watina, 2010, endyear = 2012) %>%
      collect()
    expect_migration(xg3_range, "xg3_year_range")

    # Convert lazy locs to a local data.frame first, then pass to get_xg3
    local_locs <- locs %>% select(loc_code) %>% collect()
    xg3_from_local_df <- get_xg3(local_locs, watina, 2010) %>% collect()
    expect_migration(xg3_from_local_df, "xg3_local_locs")
  })
})

