# DEVELOPER NOTE:
# Snapshots generated by the following tests can contain sensitive data and are
# therefore only stored locally via gitignore in the folder _snaps/. See the
# testing README for the recommended workflow.

# get_locs snapshot tests ------------------------------------------------------
test_that("get_locs filters locations correctly using standard attributes", {
  suppressWarnings({
    file_names <- c(
      "KAL_ZWA_locations",
      "KAL_ZWA_observation_wells",
      "area_codes",
      "area_codes_loc_type",
      "loc_validity",
      "loc_vec"
    )
    announce_files_locs(file_names)

    skip_if(getOption("test.skip_snapshot"))
    watina <- fetch_watina_connection()

    # Default validity - locations and observations
    locs <- get_locs(watina, area_codes = c("KAL", "ZWA"), loc_validity = "VLD")
    expect_locs(locs, "KAL_ZWA_locations")

    locs <- get_locs(
      watina,
      area_codes = c("KAL", "ZWA"),
      loc_validity = "VLD",
      obswells = TRUE
    )
    expect_locs(locs, "KAL_ZWA_observation_wells")

    # Area and location type filters
    locs <- get_locs(watina, area_codes = c("KAL", "KBR"))
    expect_locs(locs, "area_codes")

    locs <- get_locs(
      watina,
      area_codes = c("KAL", "KBR"),
      loc_type = c("P", "S")
    )
    expect_locs(locs, "area_codes_loc_type")

    # Select all validity options and location types
    locs <- get_locs(
      watina,
      loc_validity = c("ENT", "DEL", "CLD"),
      loc_type = c("P", "S", "R", "N", "W", "D", "L", "B")
    )
    expect_locs(locs, "loc_validity")

    # Exact location matching
    locs <- get_locs(
      watina,
      loc_vec = c("KBRP081", "KBRP090", "KBRP095", "KBRS001")
    )
    expect_locs(locs, "loc_vec")
  })
})

test_that("get_locs applies spatial queries correctly", {
  suppressWarnings({
    file_names <- c(
      "bbox",
      "mask"
    )
    announce_files_locs(file_names)

    skip_if(getOption("test.skip_snapshot"))
    watina <- fetch_watina_connection()

    # Bounding box filter
    bbox <- c(xmin = 1.4e+5, xmax = 1.7e+5, ymin = 1.6e+5, ymax = 1.9e+5)
    locs <- get_locs(watina, bbox = bbox)
    expect_locs(locs, "bbox")

    # Spatial mask filter using httr2
    wfs_url <- "https://geo.api.vlaanderen.be/VRBG/wfs" %>%
      httr2::request() %>%
      httr2::req_url_query(
        request = "GetFeature",
        typeName = "VRBG:Refprv",
        cql_filter = "NAAM='West-Vlaanderen'",
        srsName = "EPSG:31370",
        outputFormat = "text/xml; subtype=gml/3.1.1"
      )

    mymask <- sf::read_sf(wfs_url$url, crs = 31370) %>%
      sf::st_cast("GEOMETRYCOLLECTION")

    locs <- get_locs(watina, loc_validity = "VLD", mask = mymask, buffer = 0, collect = TRUE)
    expect_locs(locs, "mask")
  })
})

test_that("get_locs calculates filterdepth correctly with different filters", {
  suppressWarnings({
    file_names <- c(
      "filterdepth_guess",
      "filterdepth_na",
      "obswells"
    )
    announce_files_locs(file_names)

    skip_if(getOption("test.skip_snapshot"))
    watina <- fetch_watina_connection()

    # Guessed filterdepth correctly calculated
    locs <- get_locs(watina, area_codes = "WES", filterdepth_guess = TRUE)
    expect_locs(locs, "filterdepth_guess")

    # NA filterdepth filters correctly
    locs <- get_locs(
      watina,
      area_codes = c("KAL", "KBR"),
      loc_type = c("P", "S"),
      filterdepth_na = TRUE
    )
    expect_locs(locs, "filterdepth_na")

    # Select observation wells
    locs <- get_locs(
      watina,
      obswells = TRUE,
      area_codes = c("KAL", "KBR"),
      loc_type = c("P", "S")
    )
    expect_locs(locs, "obswells")
  })
})

test_that("get_locs applies observation wells aggregation logic correctly", {
  suppressWarnings({
    file_names <- c(
      "obswell_aggr_latest",
      "obswell_aggr_latest_fd",
      "obswell_aggr_latest_sso",
      "obswell_aggr_mean"
    )
    announce_files_locs(file_names)

    skip_if(getOption("test.skip_snapshot"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      area_codes = "WES",
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "latest"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_locs(locs, "obswell_aggr_latest")

    locs <- get_locs(
      watina,
      area_codes = "WES",
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "latest_fd"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_locs(locs, "obswell_aggr_latest_fd")

    locs <- get_locs(
      watina,
      area_codes = "WES",
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "latest_sso"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_locs(locs, "obswell_aggr_latest_sso")

    locs <- get_locs(
      watina,
      area_codes = "WES",
      filterdepth_na = TRUE,
      filterdepth_guess = TRUE,
      obswell_aggr = "mean"
    ) %>%
      select(loc_code, contains("ost"), contains("filterdepth"))
    expect_locs(locs, "obswell_aggr_mean")
  })
})

test_that("get_locs output matches exactly during extensive evaluation", {
  suppressWarnings({
    file_names <- c(
      "all",
      "all_obswells"
    )
    announce_files_locs(file_names)

    skip_if(getOption("test.skip_snapshot"))
    skip_if(getOption("test.skip_data_validation"))
    watina <- fetch_watina_connection()

    # Extensive test - all rows
    locs <- get_locs(
      watina,
      loc_validity = c("VLD"),
      loc_type = c("P", "S", "R", "N", "W", "D", "L", "B")
    )
    expect_locs(locs, "all")

    # Extensive test - all rows in observations
    locs <- get_locs(
      watina,
      obswells = TRUE,
      loc_validity = c("VLD"),
      loc_type = c("P", "S", "R", "N", "W", "D", "L", "B")
    )
    expect_locs(locs, "all_obswells")
  })
})

# get_xg3 snapshot tests -------------------------------------------------------
test_that("get_xg3 applies different filters correctly", {
  suppressWarnings({
    file_names <- c(
      "KAL_2010",
      "KAL_2010_ostend"
    )
    announce_files_xg3(file_names)

    skip_if(getOption("test.skip_snapshot"))
    watina <- fetch_watina_connection()

    locs <- get_locs(watina, area_codes = "KAL")

    xg3 <- locs %>% get_xg3(watina, 2010) %>% collect()
    expect_xg3(xg3, "KAL_2010")

    xg3 <- locs %>% get_xg3(watina, 2010, vert_crs = "ostend") %>% collect()
    expect_xg3(xg3, "KAL_2010_ostend")
  })
})

test_that("get_xg3 output matches exactly during extensive evaluation", {
  suppressWarnings({
    file_names <- c(
      "KAL_2010",
      "KAL_2010_ostend",
      "all_2010"
    )
    announce_files_xg3(file_names)

    skip_if(getOption("test.skip_snapshot"))
    skip_if(getOption("test.skip_data_validation"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      loc_validity = c("VLD"),
      loc_type = c("P", "S", "R", "N", "W", "D", "L", "B")
    )
    xg3 <- locs %>% get_xg3(watina, 2010) %>% collect()
    expect_xg3(xg3, "all_2010")
  })
})

# get_chem snapshot tests ------------------------------------------------------
test_that("get_chem applies different filters correctly", {
  suppressWarnings({
    file_names <- c(
      "ZWA",
      "ZWA_eq",
      "ZWA_thresholdNA",
      "ZWA_excludeNA",
      "ZWA_thresholdNA_excludeNA",
      "ZWA_range"
    )
    announce_files_chem(file_names)

    skip_if(getOption("test.skip_snapshot"))
    watina <- fetch_watina_connection()

    locs <- get_locs(watina, area_codes = "ZWA")

    chem <- locs %>%
      get_chem(watina, "1/1/2017", enddate = "31-12-2018") %>%
      collect()
    expect_chem(chem, "ZWA")

    chem <- locs %>%
      get_chem(watina, "1/1/2017", enddate = "31-12-2018", conc_type = "eq") %>%
      collect()
    expect_chem(chem, "ZWA_eq")

    chem <- locs %>%
      get_chem(
        watina,
        "1/1/2017",
        enddate = "31-12-2018",
        en_fecond_threshold = NA
      ) %>%
      collect()
    expect_chem(chem, "ZWA_thresholdNA")

    chem <- locs %>%
      get_chem(
        watina,
        "1/1/2017",
        enddate = "31-12-2018",
        en_exclude_na = TRUE
      ) %>%
      collect()
    expect_chem(chem, "ZWA_excludeNA")

    chem <- locs %>%
      get_chem(
        watina,
        "1/1/2017",
        enddate = "31-12-2018",
        en_exclude_na = TRUE,
        en_fecond_threshold = NA
      ) %>%
      collect()
    expect_chem(chem, "ZWA_thresholdNA_excludeNA")

    chem <- locs %>%
      get_chem(
        watina,
        "1/1/2017",
        enddate = "31-12-2018",
        en_range = c(-1, 1)
      ) %>%
      collect()
    expect_chem(chem, "ZWA_range")
  })
})

test_that("get_chem output matches exactly during extensive evaluation", {
  suppressWarnings({
    file_names <- c(
      "all_20170101"
    )
    announce_files_chem(file_names)

    skip_if(getOption("test.skip_snapshot"))
    skip_if(getOption("test.skip_data_validation"))
    watina <- fetch_watina_connection()

    locs <- get_locs(
      watina,
      loc_validity = c("VLD"),
      loc_type = c("P", "S", "R", "N", "W", "D", "L", "B")
    )
    chem <- locs %>% get_chem(watina, "1/1/2017") %>% collect()
    expect_chem(chem, "all_20170101")
  })
})
