name: Remove old artifacts

on:
  schedule:
    # Every Sunday at 1am
    - cron: '0 1 * * SUN'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 week'
        skip-recent: 5
